### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by kyber-6** [ChloePrime/AAAParticles#11]
Hello, would it be able to add Apple Silicon support?

[crash-2024-06-17_15.37.50-client.txt](https://github.com/user-attachments/files/15871913/crash-2024-06-17_15.37.50-client.txt)

**Comment by ChloePrime** [comment]
No, because I don't have any Mac devices, 
and It's too expensive for me to buy one for 20000+ CNY just for building a free minecraft mod on that platform :(

**Comment by DadamaldaDad** [comment]
Hackers build malware for Windows, because Mac users are rich, but only before they buy the Mac.
