### ISSUE TITLE
[Permission Request] Backport for version 1.19.2

### ISSUE THREAD

**Issue by min2222** [ChloePrime/AAAParticles#12]
hello! i'm a modder who mainly porting mods! this mod is very interesting and i'm planning to use in my own project.
but sadly this mod doesn't exist for 1.19.2 (my mod is both for 1.19.2 & 1.20.1) so may i ask permission for backport this to 1.19.2?
you can just upload 1.19.2 version in your project page, you don't even need to credit me!

**Comment by ChloePrime** [comment]
Permission granted :)

**Comment by min2222** [comment]
thank you! i only changed .java source codes, so don't worry!

**Comment by min2222** [comment]
also, can you create 1.19.2 branch? so i can make pull request
