### ISSUE TITLE
Anchoring vfx to an entity

### ISSUE THREAD

**Issue by ChoxRaven** [ChloePrime/AAAParticles#19]
is there any way that I could attach an effect onto an entity?
![pluh](https://github.com/user-attachments/assets/fedf4f3b-fb28-460d-ba7a-1706aa744ec4)
for example making these particles gravitate towards the player instead of a fixed point

**Comment by TheASEStefan** [comment]
I think so, yes, when adding a particle, there is a thing called "bindEntity(ExampleEntity entity)" as a method, I'll show you an example:

"AAALevel.addParticle(world, true, WEAPON_SMOKE.clone().bindOnEntity(ExampleEntity entity).scale(0.15F).position(user.getRandomX(0.25), y, user.getRandomZ(0.25)));"

**Comment by ChoxRaven** [comment]
That worked perfectly, thanks.
