### ISSUE TITLE
Error during mod loading

### ISSUE THREAD

**Issue by twohundredangels** [ChloePrime/AAAParticles#2]
Getting a near instant crash during the mod loading phase.
Running Neoforge 1.20.1; more details inside the log files

https://mclo.gs/uuOp6AK - crash report
https://mclo.gs/yzEdnCL - latest.log

**Comment by twohundredangels** [comment]
Note that this also happens with a regular Forge 1.20.1 instance, and an empty (excluding architectury) Neoforge 1.20.1 instance.

**Comment by ChloePrime** [comment]
There were some issues on the mod code abount linux.
Try version 1.20.1-1.0.8 (only available at the Github release page)

**Comment by ChloePrime** [comment]
Closed as fixed in 1.0.8
