### ISSUE TITLE
1.20.1 Incompatible with ARM (MACs)

### ISSUE THREAD

**Issue by rainysux** [ChloePrime/AAAParticles#21]
It currently crashes with MAC Forge Version 1.47.3.0 1.20.1 
Noticed this issue when trying to play Eldritch End
[latest (2).log](https://github.com/user-attachments/files/16958852/latest.2.log)
[crash-2024-09-10_23.00.49-client.txt](https://github.com/user-attachments/files/16958853/crash-2024-09-10_23.00.49-client.txt)

**Comment by ChloePrime** [comment]
MacOS is not supported due to I have no Mac devices to compile the native library :(

**Comment by ChloePrime** [comment]
Made this mod no-op on MacOS instead of crashing in version 1.2.2
