### ISSUE TITLE
Crashes on latest Nvidia drivers on Linux

### ISSUE THREAD

**Issue by HugKitten** [ChloePrime/AAAParticles#22]
This issue seems to also effect the Eldritch End mod. When launched on Linux (Arch on Wayland) and Nvidia (Nvidia Open DKMs) you get the ``libEffekseerNativeForJava.so: undefined symbol: glGenSamplers`` error. Just putting this out there so you are aware. Also this seems to only happen to the 3.0 version. Previous versions do not seem to have this issue.

**Comment by ChloePrime** [comment]
Does your system support OpenGL 3.3?

**Comment by HugKitten** [comment]
Yes, I have up to date mesa.

**Comment by HugKitten** [comment]
Scratch that. It's suppose to be up to date, but shows only as 3.2. Seems that could be cause

**Comment by ChloePrime** [comment]
> Scratch that. It's suppose to be up to date, but shows only as 3.2. Seems that could be cause

Yep that `glGenSamplers` is a part of OpenGL 3.3 standard :)

**Comment by HugKitten** [comment]
I think I know whats causing it. It's using the wrong translation layer. I was able to fix it. Thanks. I'll see if I can post some details in a moment

**Comment by HugKitten** [comment]
**I was able to fix the issue, but here are some details to anyone else who needs help.**

There are several reasons you could run into this issue. First make sure you have all your drivers up to date, and are not missing any translation layer required to use Mesa. If you use a GPU that isn't nvidia, then this will likely fix your issue. If you use nvidia, the issue seems to be that nvidia does not support openGL 3.3 through mesa. I assume this has something to do with the extra translation layer nvidia GPUs need to use mesa. You could try using other nvidia drivers, or even older ones, but be aware that this can cause your system to no longer boot if the newer kernel has compatibility issues. This may mean you need to downgrade your kernel as well. There is however another option that is much simpler. Mesa actually has a way to set which driver or api gets used.

If you use Nvidia and want to use the Vulkan API, you can use the following environmental variables:
```
__GLX_VENDOR_LIBRARY_NAME=mesa
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink
```

To do this from command line run the command ``env __GLX_VENDOR_LIBRARY_NAME=mesa __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink``
*Follow this up with your choice of launcher*

**Comment by ChloePrime** [comment]
WTF is NV doing? This problem happens on my Windows PC !

**Comment by jinkhya** [comment]
I'm also having this problem on latest nvidia drivers available on manjaro, 550.107.02.
OpenGL is 3.2 and I'm not sure how to fix this.

**Comment by Caesarovich** [comment]
I'm have OpenGL 4.6 but still get this error:
```
OpenGL version string: 4.6.0 NVIDIA 550.40.71
```
Even though this function should be part of it.

**Comment by ripjackie** [comment]
Same here as well. OpenGL 4.6 Supported:

```
OpenGL version string: 4.6.0 NVIDIA 560.35.03
```

But error happens anyways:
```
/usr/lib/jvm/java-17-openjdk/bin/java: symbol lookup error: /home/ripjackie/.local/share/PrismLauncher/instances/Prominence II RPG- Hasturian Era/minecraft/libEffekseerNativeForJava.so: undefined symbol: glGenSamplers
```

I also installed [ThreatenGL](https://modrinth.com/mod/threatengl) to force the use of OpenGL 4.6.
Before ThreatenGL:
```
[16:43:36] [Render thread/INFO]: Hardware information:
[16:43:36] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
[16:43:36] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 970/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 560.35.03)
[16:43:36] [Render thread/INFO]: OS: Linux (6.10.10-arch1-1)
```
After ThreatenGL:
```
[16:36:46] [Render thread/INFO]: Hardware information:
[16:36:46] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
[16:36:46] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 970/PCIe/SSE2 (Supports OpenGL 4.6.0 NVIDIA 560.35.03)
[16:36:46] [Render thread/INFO]: OS: Linux (6.10.10-arch1-1)
```

(Yes my hardware is ancient, but it runs fine)

**Comment by Ombrezz** [comment]
Same issue here, GTX 970 with 560 drivers. HugKitten's environment variables didn't work either.

**Comment by ripjackie** [comment]
Looks like this is an ongoing issue with Effekseer:
effekseer/Effekseer#1026

**Comment by ChloePrime** [comment]
Try version 1.4.3 which includes #33

**Comment by Caesarovich** [comment]
Thanks @ChloePrime,
When trying 1.4.3 I get the following error:

```
Caused by: java.lang.UnsatisfiedLinkError: /home/cesar/.local/share/PrismLauncher/instances/Prominence II RPG- Hasturian Era/.minecraft/libEffekseerNativeForJava.so: libGLU.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:53)
	... 12 more
```
I'm using Prism launcher with the **Prominence II RPG** modpack preset.

**Comment by ripjackie** [comment]
> Thanks @ChloePrime,
> When trying 1.4.3 I get the following error:
> 
> ```
> Caused by: java.lang.UnsatisfiedLinkError: /home/cesar/.local/share/PrismLauncher/instances/Prominence II RPG- Hasturian Era/.minecraft/libEffekseerNativeForJava.so: libGLU.so.1: cannot open shared object file: No such file or directory
> 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
> 	at java.base/java.lang.System.load(System.java:1957)
> 	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:53)
> 	... 12 more
> ```
> I'm using Prism launcher with the **Prominence II RPG** modpack preset.

Hello, this is caused by not having libGLU installed. I know the library is provided by the package `glu` in Arch Linux. 

It is an open issue, see #34, but installing this library will get you up and going.

**Comment by Caesarovich** [comment]
> It is an open issue, see #34, but installing this library will get you up and going.

Thanks for the reply,

I'm on NixOS and that didn't seem to solve the issue. Hopefully #34 will resolve in a solution that works for me.

**Comment by Frontear** [comment]
> > It is an open issue, see #34, but installing this library will get you up and going.
> 
> Thanks for the reply,
> 
> I'm on NixOS and that didn't seem to solve the issue. Hopefully #34 will resolve in a solution that works for me.

Hey 👋. I spotted you in the NixOS discord asking about this.

Given that NixOS is kinda unique in how it provides shared objects, your only choice is to `patchelf` the shared object with a reference to libGLU. You could already `buildFHSEnv` the entirety of your launcher, but I can imagine that's a bit extreme

**Comment by ripjackie** [comment]
@Caesarovich please see #36, the repo [ripjackie/EffekseerNativeForJava](https://github.com/ripjackie/EffekseerNativeForJava) should provide an easy way for you to generate the shared lib for your unique setup.
