### ISSUE TITLE
Dynamic parameters

### ISSUE THREAD

**Issue by DadamaldaDad** [ChloePrime/AAAParticles#23]
The ability to pass dynamic parameters to the particle would be very useful.
There is currently no way to use them, at least in KubeJS.

**Comment by ChloePrime** [comment]
`ParticleEmitter.setDynamicInput`

**Comment by DadamaldaDad** [comment]
How do I do that in KubeJS? The emitter is just a resource location.

**Comment by DadamaldaDad** [comment]
Sorry, closed accidentally

**Comment by DadamaldaDad** [comment]
Closed accidentally

**Comment by ChloePrime** [comment]
This is currently impossible using `AAALevel` API,
I'll investigate on this

**Comment by DadamaldaDad** [comment]
You can implement triggers too if you want, didn't find them in the code.

**Comment by ChloePrime** [comment]
Do you need to update parameters/triggers on server side?

**Comment by ChloePrime** [comment]
>One question: Can players without the mod join the server? I want this for compatibility reasons.

Impossible, but this mod is now no-op on MacOS. So you'll only need this if you have users that run client on Solaris system

**Comment by ChloePrime** [comment]
Try version 1.3.0b1 (available on curseforge)

**Comment by DadamaldaDad** [comment]
I will close this issue when it releases on Modrinth.
I want to use it for my server's modpack, mainly for Custom Machinery machines.

**Comment by DadamaldaDad** [comment]
I just realized triggers were added in 1.7, does this mean the version was updated?

**Comment by ChloePrime** [comment]
> I just realized triggers were added in 1.7, does this mean the version was updated?

Actually I forgot the core version I used. Can't find it in the source code :(

**Comment by DadamaldaDad** [comment]
You might have to test the triggers.

**Comment by ChloePrime** [comment]
Upgraded Effekseer version to 1.70e on mod version 1.4

**Comment by DadamaldaDad** [comment]
You are a very fast developer. I will reopen this issue if I run into problems.

**Comment by DadamaldaDad** [comment]
Oof. Didn't close.
