### ISSUE TITLE
Custom effek not working

### ISSUE THREAD

**Issue by DadamaldaDad** [ChloePrime/AAAParticles#25]
I have made my own smoke particles, but can't get them to work.
KubeJS assets folder:
[assets.zip](https://github.com/user-attachments/files/17022147/assets.zip)
KubeJS call:
```js
AAAParticles.addParticle(ctx.block.level, 128, new ParticleEmitterInfo("aaa_particles:crucible_smoke").position(ctx.block.x+0.5, ctx.block.y+1, ctx.block.z+0.5))
```
This works completely fine with the aaa_particles:fire. I don't know if the fire effect has some different settings, but I created the project from scratch in Effekseer 1.70e.
I'm using mod version 1.2.2 on Forge.

I'm unsure if I have to do the ReloadListenerRegistry thing, since I use the aaa_particles namespace. I don't know how I would do that with KubeJS.

**Comment by ChloePrime** [comment]
new ParticleEmitterInfo() is unstable, use ParticleEmitterInfo#create

**Comment by ChloePrime** [comment]
> I have made my own smoke particles, but can't get them to work. KubeJS assets folder: [assets.zip](https://github.com/user-attachments/files/17022147/assets.zip) KubeJS call:
> 
> ```js
> AAAParticles.addParticle(ctx.block.level, 128, new ParticleEmitterInfo("aaa_particles:crucible_smoke").position(ctx.block.x+0.5, ctx.block.y+1, ctx.block.z+0.5))
> ```
> 
> This works completely fine with the aaa_particles:fire. I don't know if the fire effect has some different settings, but I created the project from scratch in Effekseer 1.70e. I'm using mod version 1.2.2 on Forge.
> 
> I'm unsure if I have to do the ReloadListenerRegistry thing, since I use the aaa_particles namespace. I don't know how I would do that with KubeJS.

The native library version is 1.6, particles created with 1.7 will likely not work :(

**Comment by DadamaldaDad** [comment]
I tried copying the fire particle as fire2, but it also didn't work. It's most likely something to do with registration. The logs don't contain anything useful and I'm currently a bit busy.

**Comment by DadamaldaDad** [comment]
https://mclo.gs/89PsnEj
Works fine with lightning and fire, but doesn't work with fire2.

**Comment by ChloePrime** [comment]
![image](https://github.com/user-attachments/assets/847bdb4f-1d59-476c-af57-cb764352a5ea)
It's likely a fault of the asset loading or your asset setup.
The Effekseer core version is 1.6

**Comment by ChloePrime** [comment]
According to my investigation, KubeJS does not support arbitrary asset filenames.
Try use OpenLoader ?

**Comment by ChloePrime** [comment]
You can change your folder name from `Texture` to `texture` in effekseer editor and actual asset folder :)

**Comment by DadamaldaDad** [comment]
Tried with Open Loader:
`[16:08:20] [Render thread/ERROR] [minecraft/PathPackResources]: Invalid path aaa_particles:effeks/Texture/double-shockwave.png: Invalid segment 'Texture' in path 'effeks/Texture/double-shockwave.png'`

[modpack_resources.zip](https://github.com/user-attachments/files/17029580/modpack_resources.zip)

fire2 is just an exact copy of fire. I also want to know if Effekseer 1.62e would work or if you used an older version.

**Comment by DadamaldaDad** [comment]
I zipped the pack and it started working. Weird.
