### ISSUE TITLE
Culling support

### ISSUE THREAD

**Issue by DadamaldaDad** [ChloePrime/AAAParticles#26]
Culling currently doesn't work.
Implementing at least view frustum culling would be awesome for performance with lots of particles.

View frustum culling means not rendering particles outside the player's view.

**Comment by DadamaldaDad** [comment]
That's sad. I thought view frustum culling could work because it just needs the FOV, window size, camera location and angle.
Effekseer itself supports it.

**Comment by ChloePrime** [comment]
Oh I see a Java function that can accept camera parameters. Maybe calling it will enable frustum culling

**Comment by ChloePrime** [comment]
Try 1.3.1

**Comment by DadamaldaDad** [comment]
This sadly didn't fix anything. It's not on Modrinth (which doesn't matter at this point) and the version number is messed up.

**Comment by DadamaldaDad** [comment]
You can close this as not planned if you want.

**Comment by ChloePrime** [comment]
Not planned,
btw 1.3.1 is on Modrinth now :)
