### ISSUE TITLE
[Fabric 1.20.1] latest mod version crashes on launch

### ISSUE THREAD

**Issue by memphismc** [ChloePrime/AAAParticles#27]
[crash-2024-09-19_23.25.33-client.txt](https://github.com/user-attachments/files/17066031/crash-2024-09-19_23.25.33-client.txt)

previous versions dont crash like this

**Comment by memphismc** [comment]
upon further testing and inspection, this version has an unlisted dependency, that being [KubeJS](https://modrinth.com/mod/kubejs) (which in turn requires [Rhino](https://modrinth.com/mod/rhino)

this fixes the crash

**Comment by ChloePrime** [comment]
This is a bug

**Comment by ChloePrime** [comment]
Fixed in 1.3.1
