### ISSUE TITLE
How were the .dll and .so files for this project built?

### ISSUE THREAD

**Issue by ZigyTheBird** [ChloePrime/AAAParticles#29]
Hello!
I want to know how you built the .dll and .so files for this project so I can try to build one on Mac one for personal use or even for use on this repo but I doubt you will trust me to that extent
Thank you for you time :)

**Comment by ChloePrime** [comment]
By building https://github.com/effekseer/EffekseerForMultiLanguages

**Comment by ZigyTheBird** [comment]
Thanks 🙏
