### ISSUE TITLE
ParticleEmitterInfo needs Vec3 but I only have Vec3d

### ISSUE THREAD

**Issue by NotTheRealRoKur0** [ChloePrime/AAAParticles#3]
![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/6d49aedb-d44b-4d0f-bf75-3f88dfff5e07)

![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/217b2a26-9428-4960-8c5e-ac42755c9e6c)

**Comment by NotTheRealRoKur0** [comment]
I also cant just create a new Vec3 because my IDE doesnt know what a Vec3 is
![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/95b8cd4f-5ab0-4c2b-8ebe-bd3d0f95eb63)

**Comment by ChloePrime** [comment]
This project uses Mojang mapping,
you are using Yarn mapping.

**Comment by NotTheRealRoKur0** [comment]
would there be any way to use both?
because if not i'd need rewrite my whole mod just to have compat with this api.
(and other apis would probably not work with that anymore, because they also use yarn mappings)

**Comment by ChloePrime** [comment]
> would there be any way to use both? because if not i'd need rewrite my whole mod just to have compat with this api. (and other apis would probably not work with that anymore, because they also use yarn mappings)

Don't use the source code in your dependency, use only the mod jar and let Fabric Loom decompile it

**Comment by NotTheRealRoKur0** [comment]
ok, i got it.
it wasnt the apis fault.
but the versions for fabric and forge are called the same. so it downloaded the forge version instead of the fabric one!

thank you for making this api, you really did a great job!!
