### ISSUE TITLE
Adding a new Effekseer Particle: Guide

### ISSUE THREAD

**Issue by Mlodziak00** [ChloePrime/AAAParticles#4]
# Hello, Going to keep it short, this is a guide on how to use the AAA Particles library.

This Guide works similarly for both Forge and Fabric, I'll be using Fabric for this

As an example, we'll use a Modified Sample Effekseer particle made by Pierre01: [Herald](https://effekseer.github.io/en/contributes/Pierre01/index.html), 

https://github.com/ChloePrime/AAAParticles/assets/90759492/7874fe0b-906b-4e9b-9188-db3ec93b86e5

Get the Modified Particle Here: [ExampleParticle.zip](https://github.com/ChloePrime/AAAParticles/files/14604732/ExampleParticle.zip)

## Going to the Guide now (Fabric 1.20.1 Specifically):

1. We'll be going into build.gradle attaching `AAA Particle` and `Architecture API` as dependencies and while using the Modrinth Maven repository (You can also use the Curseforge Maven)

```
repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}
dependencies{
	modImplementation "maven.modrinth:aaa-particles:mIOu49Wn"
	modImplementation "maven.modrinth:architectury-api:9.2.14+fabric"
}
```

Then Load The Gradlew Changes and that's how you implement it

2. Now we add in a new Resource into our mods assets file called `effeks` like below and extract the contents of ExampleParticle.zip in there.
![image_2024-03-14_163352207](https://github.com/ChloePrime/AAAParticles/assets/90759492/845ce169-4fa2-48a9-847a-7ae65ec768c2)

3. Now we go and create a `ClientModInitializer`, and Registering a `ReloadListenerRegistry`, making sure the Identifier looks somewhat like this, but passing in your own `ModID` (First Value)
![image_2024-03-14_164125498](https://github.com/ChloePrime/AAAParticles/assets/90759492/c3ffdbe0-5173-40ee-a132-603ec2e17c95)

## That's how you add in the particles and such, but spawning them in isn't like adding in Vanilla particles, to add them I'll make an Example Spawn Item, that spawn the particle on top of any given block

1. We're going to add new static final `ParticleEmitterInfo` called HERALD, making sure we pass in a new Identifier with the `ModID` and the particles `path` (herald), then using `AAALevel` on the `useOnBlock` method, we add a new particle to the world, not forcing it and calling for HERALD.clone(),
It can have parameters like `.position, .scale, .rotation`, but we want to always call `.clone` before any of those.
In the image it is centered to the very top of the Blocks Position.
![image_2024-03-14_164842556](https://github.com/ChloePrime/AAAParticles/assets/90759492/237b88a6-928a-46b9-9e20-3988cfc3a8f1)

2. Then we register the Item itself into the Main class and you should have an item that spawns a particle like this!
NOTE, the particle isn't perfect because it's an example one, you can scale it down using `.scale(0.5F)`.

https://github.com/ChloePrime/AAAParticles/assets/90759492/fa91e027-2a8b-4273-beb3-2a1447d3390a

## Want to have it spawn like you do with Vanilla Particles? (Yes I figured it out)

1. Create a Basic Particle like you usually would [Here if you don't know how to, yes it still works](https://www.youtube.com/watch?v=cGEbensmW_c) with it's own class and registering them into the Client and Main.
```
Client
		ParticleFactoryRegistry.getInstance().register(AAAParticleExample.HERALD, HeraldParticle.Factory::new);

```
```
Main
	public static final DefaultParticleType HERALD = FabricParticleTypes.simple();
@Override
	public void onInitialize() {
		Registry.register(Registries.PARTICLE_TYPE, new Identifier("aaa-particle-example", "herald"), HERALD);
	}
```

2. Inside of the Particle interduce a new `Integer` for example `timer` and inside of the `tick()` method, pass in
```
if (timer == 0){
            timer++;
            AAALevel.addParticle(world, false, HERALD.clone().position(this.x, this.y, this.z)); /// This is the same as for the Item
        }
```
Were doing it on the 0th tick so it only spawns in 1 time.

3. if you did everything correctly, now the Particle should be inside of the `/particle` command and should summon without any issues! (Hopefully)

https://github.com/ChloePrime/AAAParticles/assets/90759492/a792cbda-7563-431b-b19b-88ddd0880d3f

**Comment by kyber-6** [comment]
Thank you for this tutorial, friend. I have a question in regards to how you export other Effekseer particles, as I am unable to make this work with other sample particles.

**Comment by Raia05** [comment]
is there a way to do it via resourse packs to replace existing particles?

**Comment by Tooop22** [comment]
This tutorial would've been helpful if you actually showed us how to export the particles to be used.

**Comment by Tooop22** [comment]
> Thank you for this tutorial, friend. I have a question in regards to how you export other Effekseer particles, as I am unable to make this work with other sample particles.

You gotta change the texture location of the particle to the ones in your mod(using the effekseer program). Don't know why OP didn't include since it's literally an important step.

**Comment by Freddy1o1** [comment]
Do you know how you would go about implementing this into mcreator?

**Comment by ZigyTheBird** [comment]
@ChloePrime you should really just make a wiki for this repo and copy and paste this tutorial there

**Comment by TheASEStefan** [comment]
Hey, small question here. For some reason, yes, my implementation on Forge does work, and I now have 3 particles in game, but they were all made on top of a sample one, a muzzle flash one. I deleted the muzzle sparks and etc and only kept the smoke, and played with those to obtain 3 new particles. But for some reason, the old particle, the entire muzzle flash particle basically straight up appears out of nowhere in game and I don't know why that is and it only happens when I right-click. Like there's NO actual leftovers of that particle in the assets folder or actually make the particle appear with code, NOTHING. Can someone help?

**Comment by TheASEStefan** [comment]
Even WORSE. Apparently, the muzzle flash particle also appears when I left click with ANYTHING except the empty arm of the player. This is a very weird issue, so can somebody help?

**Comment by TheASEStefan** [comment]
@ChloePrime FOUND THE ISSUE. So apparently the latest version of aaa particles causes this. I have installed version 1.0,8 and now it works, hopefully you will notice this bug!!

**Comment by 325bob** [comment]
@Mlodziak00 Can you give us the code you made in the example?

**Comment by makozort** [comment]
@Mlodziak00 how can I contact you? I wish to ask for help setting this up in modern versions

**Comment by JosamX** [comment]
For those wondering: I couldn't find anything about MCreator with AAA Particles, but I found [this](https://www.youtube.com/watch?v=ZEepTXI1cX4) guide in Japanese, better than nothing I guess.

**Comment by ChloePrime** [comment]
Moved this to the wiki section of this repo

**Comment by Freddy1o1** [comment]
> Hey, small question here. For some reason, yes, my implementation on Forge does work, and I now have 3 particles in game, but they were all made on top of a sample one, a muzzle flash one. I deleted the muzzle sparks and etc and only kept the smoke, and played with those to obtain 3 new particles. But for some reason, the old particle, the entire muzzle flash particle basically straight up appears out of nowhere in game and I don't know why that is and it only happens when I right-click. Like there's NO actual leftovers of that particle in the assets folder or actually make the particle appear with code, NOTHING. Can someone help?

hey srry i dont have an answer to your problem but you said you got it working for forge how did you do that i cant get it to work at all

**Comment by DAKOChTH** [comment]
Can I have a sample of your mod?
