### ISSUE TITLE
Is a 1.21 port planned?

### ISSUE THREAD

**Issue by ZigyTheBird** [ChloePrime/AAAParticles#43]
I would really appreciate it :)
I made my own fork and ported it to 1.21 but sadly it's a bit broken and IDK how to fix it

**Comment by ChloePrime** [comment]
What's broken?

**Comment by ChloePrime** [comment]
![image](https://github.com/user-attachments/assets/9c27e051-d5c0-4cb2-b3dc-e12a51316b6b)
I failed to setup dev environment on MC1.21 :(

**Comment by ZigyTheBird** [comment]
Do you have this repository added?:
	maven {
		// saps.dev Maven (KubeJS and Rhino)
		url = "https://maven.saps.dev/minecraft"
		content {
			includeGroup "dev.latvian.mods"
		}
	}
If that isn't the issue then IDK
Here is a video of the bug I am having: https://cdn.discordapp.com/attachments/1285619155244155011/1296461041919725649/2024-10-17_16-40-50.mp4?ex=67125eef&is=67110d6f&hm=e48342f61f92dc3239c80247c80cd4389054da2b11db82dc678bed539a525fec&
Normally the particles would be at the tip of the player's hand but rn when I look around they bug out
Here is my repo if you wanna take a look: https://github.com/ZigyTheBird/AAAParticles-Zigys-Edition

**Comment by ChloePrime** [comment]
Port uploaded

**Comment by ChloePrime** [comment]
An amazing fact that hand rendering is working fine when Iris is installed and shader is enabled

**Comment by ZigyTheBird** [comment]
@ChloePrime thanks a lot it works perfectly!
But please also upload it to Modrinth 🙏

**Comment by ChloePrime** [comment]
Uploaded~
