### ISSUE TITLE
Parts of particle get rendered even behind walls/entities

### ISSUE THREAD

**Issue by ZigyTheBird** [ChloePrime/AAAParticles#46]
Here is a clip of it happening: https://cdn.discordapp.com/attachments/1163186803176640583/1298279599477751808/2024-10-22_17-07-23.mp4?ex=6718fc99&is=6717ab19&hm=1e5146684dfefe8795ba24c28faa34105b4aa7d0fe9127370503964b69d3eb68&
Here is the effek with this issue: [Bugged Effek.zip](https://github.com/user-attachments/files/17477117/Bugged.Effek.zip)

**Comment by ZigyTheBird** [comment]
I don't remember if this started happening after I ported to 1.21 or after I switched the blend mode from additive to blend

**Comment by ZigyTheBird** [comment]
Just found out that particles aren't visible while the game graphics setting is set to fabulous
Not gonna make a whole new issue just for that

**Comment by ChloePrime** [comment]
> Just found out that particles aren't visible while the game's graphics setting is set to fabulous Not gonna make a whole new issue just for that

`Fabulous` will never be supported

**Comment by ChloePrime** [comment]
This `Bugged effek` has deliberately disabled depth testing in Effekseer editor.
![image](https://github.com/user-attachments/assets/14345401-b572-436d-aaa2-f8233b21cd17)
So this is the intended behavior.
