### ISSUE TITLE
Cant use BindOnEntity on Mobs only myself

### ISSUE THREAD

**Issue by NotTheRealRoKur0** [ChloePrime/AAAParticles#5]
this doesnt work:
![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/f83abd89-a32e-4930-9f7f-7d776779ed94)

but this:
![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/bcd072e6-b160-4257-80c3-24922fd5a43c)
(getCaster() returns PlayerEntity)

and this:
![image](https://github.com/ChloePrime/AAAParticles/assets/98748787/293becdb-8afe-41f0-b5f9-d4fccb3348ab)
(entity() returns Entity which player is looking at)

why is that so?

**Comment by ChloePrime** [comment]
try use `ParticleEmitterInfo.create()` instead of `new ParticleEmitterInfo()`

**Comment by ChloePrime** [comment]
try replace `new ParticleEmitterInfo()` with `ParticleEmitterInfo.create()`,
and set `entitySpaceRelativePosition(x, y, z)`

**Comment by ChloePrime** [comment]
![image](https://github.com/ChloePrime/AAAParticles/assets/43518523/a530a037-103b-4af5-b9eb-c9235ab32c54)
this works on my environment:
```java
        Optional.ofNullable(mc.crosshairPickEntity).map(Entity::getId)
                .ifPresent(eid -> {
                    var dim = Objects.requireNonNull(mc.level).dimension();
                    var srv = Objects.requireNonNull(mc.getSingleplayerServer());
                    srv.execute(() -> {
                        var srvLevel = Objects.requireNonNull(srv.getLevel(dim));
                        AAALevel.addParticle(srvLevel, new ParticleEmitterInfo(DEBUG_PARTICLE)
                                        .bindOnEntity(Objects.requireNonNull(srvLevel.getEntity(eid)))
//                        .position(0, 1.8, 0)
//                        .entitySpaceRelativePosition(0.5, 0, -0.5)
//                        .rotation((float) (Math.PI / 2), 0, 0)
                        );
                    });
                });
```
